#define FLOW_TAP_TERM 60
#define CHORDAL_HOLD
#define TAPPING_TERM 300
#define QUICK_TAP_TERM 120

#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define CAPS_WORD_INVERT_ON_SHIFT

#define COMBO_TERM 30

#define USB_SUSPEND_WAKEUP_DELAY 0
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
